language: python
python:
  - "3.6"
  - "2.7"

install:
  - pip install tox-travis codecov .[test]

script:
  # TODO - Look into how this is managed in:
  #   - https://github.com/tox-dev/tox-travis/blob/master/.travis.yml
  #   - https://docs.travis-ci.com/user/languages/python/#using-tox-as-the-build-script
  - tox

after_success:
  # This is really hacky. There must be a better way of handling this.
  #- py.test --cov=./plpacker ./tests/
  - python setup.py test --addopt --cov=./plpacker
  - codecov
